# Generated by Django 2.1.7 on 2019-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('carousel_num', models.CharField(blank=True, max_length=10, null=True)),
                ('img', models.CharField(max_length=200)),
                ('is_active', models.CharField(blank=True, max_length=10, null=True)),
                ('text', models.TextField()),
                ('text_align', models.CharField(blank=True, default='text-right', max_length=20, null=True)),
            ],
        ),
    ]
