# Generated by Django 2.1.7 on 2019-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190318_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/', width_field='width_field'),
        ),
    ]
