# Generated by Django 2.1.7 on 2019-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190319_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
