# Generated by Django 2.1.7 on 2019-03-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190319_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='img',
        ),
    ]
